### PR TITLE
internal/states/statemgr: handle ignored errors

### PR DESCRIPTION
**Pull request by alrs**
Fix https://github.com/opentffoundation/opentf/issues/278

This handles ignored `err` variables in `internal/states/statemgr`.

I'm happy to change this to be more aggressive and return wrapped errors instead of just logging.

### CODE REVIEW

**Comment by DicsyDel** [comment]
Hi @alrs,
First of all, let me thank you for creating this PR and willingness to contribute to OpenTF.

We just started our path on making opentf truly open and community driven so a lot of processes and guidelines are still being created and polished to ensure long-term success of this project. With that being said, your PR makes sense and valid, but I'd ask you to create an issue first and convert this PR to a draft to make sure that some basic process is being followed. 

Thanks,
Igor

**Comment by alrs** [comment]
@DicsyDel I've created an issue, and linked to it.

Could you give CI the green-light to test this PR?

**Comment by DicsyDel** [comment]
@alrs Looks solid, thanks. Would you mind also create a changelog entry describing this fix.

**Comment by alrs** [comment]
@DicsyDel CHANGELOG updated.

**Review by cube2222 — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
