### PR TITLE
feat: add apk, deb and rpm package build to goreleaser

### LINKED ISSUE #160: Create releases for all platforms (Alpine, Debian, Windows, etc.)
After creating an initial release process, and creating OpenTF binaries, we'd like to add support to all other platforms (or at least the major ones)

Alpine, Debian, Windows, etc.

### PR DESCRIPTION
**Pull request by thschue**
Resolves #160 

## Target Release

1.6.0

### ENHANCEMENTS
- Packages for deb, rpm and apk are built in the release process and published as release artifacts with goreleaser

### CODE REVIEW

**Review by eranelbaz — COMMENTED** [review]
Please alter `changelog.md`

**Comment by cube2222** [comment]
@eranelbaz I don't think this should go into the changelog. Those builds were already there, and we're just bringing them back here. There's no functionality change here.

**Comment by eranelbaz** [comment]
@cube2222 sounds reasonable 😃

**Review by cube2222 — APPROVED** [review]
Thanks for the contribution @thschue!

**Pull request merged**
